package dependencies

object Versions {

    val androidx_test_ext = "1.1.3"
    val appcompat = "1.4.1"
    val constraintlayout = "2.1.3"
    val coroutines_version = "1.5.2"
    val coroutines_play_services = "1.3.2"
    val dagger = "2.41"
    val espresso_core = "3.4.0"
    val espresso_idling_resource = "3.2.0"
    val firebase_firestore = "21.4.2"
    val firebase_analytics = "17.4.0"
    val firebase_crashlytics = "2.10.1"
    val firebase_auth = "19.3.0"
    val fragment_version = "1.2.0"
    val fabric_version = "1.31.2"
    val gradle = "7.1.2"
    val gson = "2.9.0"
    val glide = "4.13.1"
    val junit4 = "4.13.2"
    val junit_jupiter_version = "5.6.0"
    val kotlin = "1.6.10"
    val ktx = "1.7.0"
    val leak_canary = "2.0"
    val lifecycle_version = "2.2.0"
    val legacy_support = "1.0.0"
    val material_design = "1.5.0"
    val material_dialogs = "3.2.1"
    val markdown_processor = "0.1.3"
    val mockk_version = "1.9.2"
    val navigation_components = "2.4.1"
    val play_services = "4.3.3"
    val play_core = "1.7.1"
    val room = "2.4.2"
    val retrofit2_version = "2.6.0"
    val swipe_refresh_layout = "1.1.0"
    val test_runner = "1.2.0"
    val test_core = "1.2.0"

}